trigger:
- main

pr:
- none

stages:
- stage: ci_stage
  displayName: Continuous Integration stage
  jobs:
  - job: ci_job
    displayName: Continuous Integration job
    steps:
    - bash: |
        git remote set-url origin https://merkatorgis:$(GITHUB_PASSWORD)@github.com/merkatorgis/docker4gis-postgis.git
      displayName: Git login
    
    - bash: |
        echo '$(DOCKER_PASSWORD)' | docker login -u=docker4gis --password-stdin docker.io
      displayName: Docker login
    
    - bash: |
        git config --global user.email 'pipeline@azure.com'
        git config --global user.name 'Azure Pipeline'
      displayName: Git config
    
    - bash: |
        git checkout -b main
        git push --set-upstream origin main
      displayName: Git undo detached state
    
    # Use --no-save, because another push will follow.
    - bash: |
        npx --yes docker4gis@latest push --no-save 16 3.5
      displayName: docker4gis push --no-save 16 3.5
    
    # Do provide the default values for the build parameters, so that they're
    # included in the image's tag. Also, do this one as the last push, so that
    # this one gets the "latest" tag.
    - bash: |
        npx --yes docker4gis@latest push 17 3.5
      displayName: docker4gis push 17 3.5
